first_project/urls.py
from django.contrib import admin
from django.urls import path
from restaurant.views import index, rest1, rest2, rest3, rest4
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservations/', index, name='reservations'),
    path('rest1', rest1, name='rest1'),
    path('rest2', rest2, name='rest2'),
    path('rest3', rest3, name='rest3'),
    path('rest4', rest4, name='rest4'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurant/models.py
from django.db import models

# Create your models here.

class Restaurant(models.Model):
    name = models.CharField(max_length=30)
    date_opened = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    opening_hour = models.TimeField(blank=True, null=True)
    closing_hour = models.TimeField(blank=True, null=True)

    def __str__(self):
        return self.name

class Employee(models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    date_birth = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    restaurant = models.ForeignKey('Restaurant', on_delete=models.CASCADE, blank=True, null=True)

class Table(models.Model):
    number = models.IntegerField(blank=True, null=True)
    chairs = models.IntegerField(blank=True, null=True)
    restaurant = models.ForeignKey('Restaurant', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.number)


class Reservation(models.Model):
    table = models.ForeignKey('Table', on_delete=models.CASCADE, blank=True, null=True)
    date_time = models.DateTimeField(blank=True, null=True)
    desc = models.TextField(blank=True, null=True)
    name = models.CharField(max_length=30)

    def __str__(self):
        return str(self.table.number) + " - " + self.name

restaurant/forms.py
from django.forms import ModelForm
from .models import Reservation

class ReservationForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(ReservationForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Reservation
        fields = ["table", "date_time", "desc", "name"]

restaurant/views.py
from django.shortcuts import render, redirect
from .forms import ReservationForm

def index(request):
    if request.method == "POST":
        form_data = ReservationForm(data=request.POST)
        if form_data.is_valid():
            reservation = form_data.save()
            return redirect("reservations")
    context = {"form": ReservationForm}
    return render(request, "index.html", context=context)

def rest1(request):
    if request.method == "POST":
        form_data = ReservationForm(data=request.POST)
        if form_data.is_valid():
            print(form_data)
            reservation = form_data.save()
            return redirect("rest1")
    context = {"form": ReservationForm}
    return render(request, "rest1.html", context=context)

def rest2(request):
    if request.method == "POST":
        form_data = ReservationForm(data=request.POST)
        if form_data.is_valid():
            reservation = form_data.save()
            return redirect("rest2")
    context = {"form": ReservationForm}
    return render(request, "rest2.html", context=context)

def rest3(request):
    if request.method == "POST":
        form_data = ReservationForm(data=request.POST)
        if form_data.is_valid():
            reservation = form_data.save()
            return redirect("rest3")
    context = {"form": ReservationForm}
    return render(request, "rest3.html", context=context)

def rest4(request):
    if request.method == "POST":
        form_data = ReservationForm(data=request.POST)
        if form_data.is_valid():
            reservation = form_data.save()
            return redirect("rest4")
    context = {"form": ReservationForm}
    return render(request, "rest4.html", context=context)

# Create your views here.

restaurant/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            background: rgba(0, 0, 0, 0.7) url({% static 'slika.jpg' %});
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
             background-blend-mode: darken;
        }
        *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    font-family: 'Josefin Sans', sans-serif;
}

.header{
    width: 100%;
    background-color: rgba(0,0,0,.4);
}

.header ul{
    text-align: center;
}

.header ul li{
    list-style: none;
    display: inline-block;
}

.header ul li a{
    display: block;
    text-decoration: none;
    text-transform: uppercase;
    color: #b1d726;
    font-size: 20px;
    font-family: 'Raleway', sans-serif;
    letter-spacing: 2px;
    font-weight: 600;
    padding: 25px;
    transition: all ease 0.5s;
}

.header ul li a:hover{
    background-color: rgba(246, 111, 114, 0.55);
}

.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 42%;
    margin-top: 30px;
}




    </style>
</head>
<body>
    <div class="header">
            <ul>
                <li><a href="{% url 'rest1' %}">Rest1</a></li>
                <li><a href="{% url 'rest2' %}">Rest2</a></li>
                <li><a href="{% url 'rest3' %}">Rest3</a></li>
                <li><a href="{% url 'rest4' %}">Rest4</a></li>
            </ul>
    </div>
</body>
</html>

restaurant/templates/rest1.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <title>Title</title>
    <style>
        body {
            background: rgba(0, 0, 0, 0.7) url({% static 'slika.jpg' %});
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
             background-blend-mode: darken;
        }
        *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    font-family: 'Josefin Sans', sans-serif;
}

.header{
    width: 100%;
    background-color: rgba(0,0,0,.4);
}

.header ul{
    text-align: center;
}

.header ul li{
    list-style: none;
    display: inline-block;
}

.header ul li a{
    display: block;
    text-decoration: none;
    text-transform: uppercase;
    color: #b1d726;
    font-size: 20px;
    font-family: 'Raleway', sans-serif;
    letter-spacing: 2px;
    font-weight: 600;
    padding: 25px;
    transition: all ease 0.5s;
}

.header ul li a:hover{
    background-color: rgba(246, 111, 114, 0.55);
}

.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 42%;
    margin-top: 30px;
}

p label{
    color: white;
}

form{
    width:1000px;
    margin: auto;
}



    </style>
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
    $("id_date_time").attr("type", "datetime-local");
        $("#rest").click(function (event) {
            x_coordinate = event.clientX //x koordinata na klikot
            y_coordinate = event.clientY // y koordinata na klikot
            console.log(x_coordinate) //pecatenje na x koordinata (desen klik vo browser, pa inspect, pa gore ima console pishuva)
            console.log(y_coordinate)
            if(x_coordinate>=820 && x_coordinate<=896 && y_coordinate>=160 && y_coordinate<=233){
                $("#id_table").val("1")
                console.log("Table 1") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=660 && x_coordinate<=740 && y_coordinate>=233 && y_coordinate<=314){
            $("#id_table").val("2")
                console.log("Table 2") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=740 && x_coordinate<=820 && y_coordinate>=233 && y_coordinate<=314){
            $("#id_table").val("3")
                console.log("Table 3") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=820 && x_coordinate<=900 && y_coordinate>=233 && y_coordinate<=314){
            $("#id_table").val("4")
                console.log("Table 4") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=660 && x_coordinate<=740 && y_coordinate>=314 && y_coordinate<=400){
                        $("#id_table").val("5")
                console.log("Table 5") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=740 && x_coordinate<=820 && y_coordinate>=314 && y_coordinate<=400){
                        $("#id_table").val("6")
                console.log("Table 6") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=820 && x_coordinate<=900 && y_coordinate>=314 && y_coordinate<=400){
                        $("#id_table").val("7")
                console.log("Table 7") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=329 && x_coordinate<=376 && y_coordinate>=215 && y_coordinate<=285){
                        $("#id_table").val("8")
                console.log("Table 8") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=393 && x_coordinate<=424 && y_coordinate>=317 && y_coordinate<=343){
                        $("#id_table").val("9")
                console.log("Table 9") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }

        })
    })
</script>
<body>
<div class="back">
    <div class="header">
            <ul>
                <li><a href="{% url 'rest1' %}">Rest1</a></li>
                <li><a href="{% url 'rest2' %}">Rest2</a></li>
                <li><a href="{% url 'rest3' %}">Rest3</a></li>
                <li><a href="{% url 'rest4' %}">Rest4</a></li>
            </ul>
    </div>
<img id="rest" src="{% static '1.png' %}" alt="slika" class="center">
</div>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
<button class="btn btn-success">Submit</button>
</form>
</body>
<script>
    $(document).ready(function () {
    console.log("primer")
    $("#id_date_time").attr("type", "datetime-local");})
    </script>
</html>

restaurant/templates/rest2.html
<!DOCTYPE html>
<html lang="en">
<head>
        {% load static %}
    <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <title>Title</title>
    <style>
        body {
            background: rgba(0, 0, 0, 0.7) url({% static 'slika.jpg' %});
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
             background-blend-mode: darken;
        }
        *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    font-family: 'Josefin Sans', sans-serif;
}

.header{
    width: 100%;
    background-color: rgba(0,0,0,.4);
}

.header ul{
    text-align: center;
}
p label{
    color: white;
}

form{
    width:1000px;
    margin: auto;
}
.header ul li{
    list-style: none;
    display: inline-block;
}

.header ul li a{
    display: block;
    text-decoration: none;
    text-transform: uppercase;
    color: #b1d726;
    font-size: 20px;
    font-family: 'Raleway', sans-serif;
    letter-spacing: 2px;
    font-weight: 600;
    padding: 25px;
    transition: all ease 0.5s;
}

.header ul li a:hover{
    background-color: rgba(246, 111, 114, 0.55);
}

.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 42%;
    margin-top: 30px;
}




    </style>
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("img").click(function (event) {
            x_coordinate = event.clientX //x koordinata na klikot
            y_coordinate = event.clientY // y koordinata na klikot
            console.log(x_coordinate) //pecatenje na x koordinata (desen klik vo browser, pa inspect, pa gore ima console pishuva)
            console.log(y_coordinate)
            if(x_coordinate>=520 && x_coordinate<=560 && y_coordinate>=161 && y_coordinate<=213){
                console.log("Table 1") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=584 && x_coordinate<=647 && y_coordinate>=157 && y_coordinate<=221){
                console.log("Table 2") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=486 && x_coordinate<=533 && y_coordinate>=276 && y_coordinate<=310){
                console.log("Table 3") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=548 && x_coordinate<=596 && y_coordinate>=276 && y_coordinate<=311){
                console.log("Table 4") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=606 && x_coordinate<=652 && y_coordinate>=274 && y_coordinate<=306){
                console.log("Table 5") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=363 && x_coordinate<=394 && y_coordinate>=340 && y_coordinate<=359){
                console.log("Table 6") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=375 && x_coordinate<=393 && y_coordinate>=382 && y_coordinate<=400){
                console.log("Table 7") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=365 && x_coordinate<=392 && y_coordinate>=422 && y_coordinate<=442){
                console.log("Table 8") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=457 && x_coordinate<=484 && y_coordinate>=440 && y_coordinate<=462){
                console.log("Table 9") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=528 && x_coordinate<=554 && y_coordinate>=441 && y_coordinate<=460){
                console.log("Table 10") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
        })
    })
</script>
<body>
<div class="back">
    <div class="header">
            <ul>
                <li><a href="{% url 'rest1' %}">Rest1</a></li>
                <li><a href="{% url 'rest2' %}">Rest2</a></li>
                <li><a href="{% url 'rest3' %}">Rest3</a></li>
                <li><a href="{% url 'rest4' %}">Rest4</a></li>
            </ul>
    </div>
<img  src="{% static '4.png' %}" alt="slika" class="center">
</div>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
{{form.as_p}}
<button class="btn btn-success">Submit</button>
</form>
</body>
<script>
    $(document).ready(function () {
    console.log("primer")
    $("#id_date_time").attr("type", "datetime-local");})
    </script>

</html>

restaurant/templates/rest3.html
<!DOCTYPE html>
<html lang="en">
<head>
        {% load static %}
    <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <title>Title</title>
    <style>
        body {
            background: rgba(0, 0, 0, 0.7) url({% static 'slika.jpg' %});
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
             background-blend-mode: darken;
        }
        p label{
    color: white;
}

form{
    width:1000px;
    margin: auto;
}
        *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    font-family: 'Josefin Sans', sans-serif;
}

.header{
    width: 100%;
    background-color: rgba(0,0,0,.4);
}

.header ul{
    text-align: center;
}

.header ul li{
    list-style: none;
    display: inline-block;
}

.header ul li a{
    display: block;
    text-decoration: none;
    text-transform: uppercase;
    color: #b1d726;
    font-size: 20px;
    font-family: 'Raleway', sans-serif;
    letter-spacing: 2px;
    font-weight: 600;
    padding: 25px;
    transition: all ease 0.5s;
}

.header ul li a:hover{
    background-color: rgba(246, 111, 114, 0.55);
}

.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 42%;
    margin-top: 30px;
}




    </style>
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("img").click(function (event) {
            x_coordinate = event.clientX //x koordinata na klikot
            y_coordinate = event.clientY // y koordinata na klikot
            console.log(x_coordinate) //pecatenje na x koordinata (desen klik vo browser, pa inspect, pa gore ima console pishuva)
            console.log(y_coordinate)
            if(x_coordinate>=479 && x_coordinate<=528 && y_coordinate>=169 && y_coordinate<=191){
                console.log("Table 1") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=540 && x_coordinate<=586 && y_coordinate>=166 && y_coordinate<=188){
                console.log("Table 2") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=495 && x_coordinate<=534 && y_coordinate>=217 && y_coordinate<=251){
                console.log("Table 3") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=545 && x_coordinate<=580 && y_coordinate>=217 && y_coordinate<=249){
                console.log("Table 4") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=589 && x_coordinate<=628 && y_coordinate>=218 && y_coordinate<=251){
                console.log("Table 5") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=494 && x_coordinate<=540 && y_coordinate>=283 && y_coordinate<=301){
                console.log("Table 6") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=553 && x_coordinate<=596 && y_coordinate>=284 && y_coordinate<=301){
                console.log("Table 7") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=607 && x_coordinate<=652 && y_coordinate>=281 && y_coordinate<=300){
                console.log("Table 8") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
            if(x_coordinate>=649 && x_coordinate<=668 && y_coordinate>=181 && y_coordinate<=265){
                console.log("Table 9") //go ogranichuvame x vo granici 30 do 60 i isto za y
            }
        })
    })
</script>
<body>
<div class="back">
    <div class="header">
            <ul>
                <li><a href="{% url 'rest1' %}">Rest1</a></li>
                <li><a href="{% url 'rest2' %}">Rest2</a></li>
                <li><a href="{% url 'rest3' %}">Rest3</a></li>
                <li><a href="{% url 'rest4' %}">Rest4</a></li>
            </ul>
    </div>
<img  src="{% static '7.png' %}" alt="slika" class="center">
</div>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
{{form.as_p}}
<button class="btn btn-success">Submit</button>
</form>
</body>
<script>
    $(document).ready(function () {
    console.log("primer")
    $("#id_date_time").attr("type", "datetime-local");})
    </script>
</html>

restaurant/templates/rest4.html
<!DOCTYPE html>
<html lang="en">
<head>
        {% load static %}
    <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <title>Title</title>
    <style>
        body {
            background: rgba(0, 0, 0, 0.7) url({% static 'slika.jpg' %});
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
             background-blend-mode: darken;
        }
        p label{
    color: white;
}

form{
    width:1000px;
    margin: auto;
}
        *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
    font-family: 'Josefin Sans', sans-serif;
}

.header{
    width: 100%;
    background-color: rgba(0,0,0,.4);
}

.header ul{
    text-align: center;
}

.header ul li{
    list-style: none;
    display: inline-block;
}

.header ul li a{
    display: block;
    text-decoration: none;
    text-transform: uppercase;
    color: #b1d726;
    font-size: 20px;
    font-family: 'Raleway', sans-serif;
    letter-spacing: 2px;
    font-weight: 600;
    padding: 25px;
    transition: all ease 0.5s;
}

.header ul li a:hover{
    background-color: rgba(246, 111, 114, 0.55);
}

.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 42%;
    margin-top: 30px;
}



    </style>
</head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    $("img").click(function (event) {
      x_coordinate = event.clientX //x koordinata na klikot
      y_coordinate = event.clientY // y koordinata na klikot
      console.log(x_coordinate) //pecatenje na x koordinata (desen klik vo browser, pa inspect, pa gore ima console pishuva)
      console.log(y_coordinate)
      if(x_coordinate>=404 && x_coordinate<=519 && y_coordinate>=129 && y_coordinate<=169){
        console.log("Table 1") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=388 && x_coordinate<=404 && y_coordinate>=295 && y_coordinate<=321){
        console.log("Table 2") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=413 && x_coordinate<=425 && y_coordinate>=292 && y_coordinate<=324){
        console.log("Table 3") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=436 && x_coordinate<=450 && y_coordinate>=292 && y_coordinate<=320){
        console.log("Table 4") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=456 && x_coordinate<=471 && y_coordinate>=294 && y_coordinate<=321){
        console.log("Table 5") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=541 && x_coordinate<=614 && y_coordinate>=241 && y_coordinate<=297){
        console.log("Table 6") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=540 && x_coordinate<=612 && y_coordinate>=317 && y_coordinate<=341){
        console.log("Table 7") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=313 && x_coordinate<=357 && y_coordinate>=205 && y_coordinate<=245){
        console.log("Table 8") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=331 && x_coordinate<=368 && y_coordinate>=264 && y_coordinate<=294){
        console.log("Table 9") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=313 && x_coordinate<=352 && y_coordinate>=317 && y_coordinate<=353){
        console.log("Table 10") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=372 && x_coordinate<=409 && y_coordinate>=377 && y_coordinate<=409){
        console.log("Table 11") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=424 && x_coordinate<=464 && y_coordinate>=361 && y_coordinate<=393){
        console.log("Table 12") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=540 && x_coordinate<=577 && y_coordinate>=378 && y_coordinate<=409){
        console.log("Table 13") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
      if(x_coordinate>=587 && x_coordinate<=629 && y_coordinate>=363 && y_coordinate<=397){
        console.log("Table 14") //go ogranichuvame x vo granici 30 do 60 i isto za y
      }
    })
  })
</script>
<body>
<div class="back">
    <div class="header">
            <ul>
                <li><a href="{% url 'rest1' %}">Rest1</a></li>
                <li><a href="{% url 'rest2' %}">Rest2</a></li>
                <li><a href="{% url 'rest3' %}">Rest3</a></li>
                <li><a href="{% url 'rest4' %}">Rest4</a></li>
            </ul>
    </div>
<img  src="{% static '2.png' %}" alt="slika" class="center">
</div>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
{{form.as_p}}
<button class="btn btn-success">Submit</button>
</form>
</body>
<script>
    $(document).ready(function () {
    console.log("primer")
    $("#id_date_time").attr("type", "datetime-local");})
    </script>
</html>